title: smartDEV - Самые лучшее об IT
name: smartDEV
description: Новости мира IT, технологии и современные гаджеты
keyword: лучшие пк комплектующие, выбор комплектующипх пк, лучшие девайсы
owner: Тройна Ольга Андреевна
copyrightowner: Тройне Ольге Андреевне

themecolor: '#202225'
imagehome: img/geektop.jpg
url: 'http://localhost:3000'
baseurl: '/'

plugins: [jekyll-paginate-v2]
category_dir: blog
pagination:
  enabled: true
  per_page: 9
  title: ':title - Страница :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

future: true

exclude:
  [
    'node_modules',
    'gulpfile.js',
    'package.json',
    'package-lock.json',
    'js/common.js',
    'npm-debug.log',
    'scss',
    '**/Thumbs.db',
    'libs',
  ]

soc:
  <li><a href="https://www.facebook.com/frontendercode" target="_blank"><i class="fa fa-vk"></i></a></li>
  <li><a href="https://www.facebook.com/frontendercode" target="_blank"><i class="fa fa-facebook"></i></a></li>
  <li><a href="https://www.facebook.com/frontendercode" target="_blank"><i class="fa fa-odnoklassniki"></i></a></li>
  <li><a href="https://www.facebook.com/frontendercode" target="_blank"><i class="fa fa-instagram"></i></a></li>
  <li><a href="https://www.facebook.com/frontendercode" target="_blank"><i class="fa fa-rss"></i></a></li>

copyright: Копирование контента и размещение на других сайтах запрещено.
